Ddcnl 7737
hmrc/nisp-frontend pull request #510
Opened 2023-09-13 10:22 UTC by emrawsy

# Pull Request Checklist
- Add/update Welsh translation if required.
- Add any logging needed for Bridge Team monitoring.
- Add unit/acceptance/performance tests for new features.
- Make sure code coverage has not dropped.
- Run the [cysp-acceptance-test](https://github.com/hmrc/cysp-acceptance-test).
- Run the [nisp-sapeak-performance-tests](https://github.com/hmrc/nisp-sapeak-performance-tests).
- Perform relevant accessibility checks.
- Test manually in browser if required.
- Make any environment configuration changes/checks if needed.

2023-09-18 13:11 UTC, smithrebecca submitted a review, later dismissed

2023-09-18 15:06 UTC, lewey requested changes

2023-09-21 07:45 UTC, emrawsy commented on app/uk/gov/hmrc/nisp/views/nirecordpage.scala.html
> +  pageTitle = if(user.livesAbroad) { messages("nisp.nirecord.heading.uk") } else if (niRecord.numberOfGaps > 0) {
ideally it would be passed in yes but it meant changing a lot more, I'll neaten this bit up though.

2023-09-22 11:22 UTC, emrawsy commented on app/uk/gov/hmrc/nisp/views/nirecordpage.scala.html
> +             else messages("nisp.nirecord.heading"),
added tests

2023-09-22 11:22 UTC, emrawsy commented on app/uk/gov/hmrc/nisp/views/nirecordpage.scala.html
> +  pageTitle = if(user.livesAbroad) { messages("nisp.nirecord.heading.uk") } else if (niRecord.numberOfGaps > 0) {
refactored this work

2023-09-26 08:53 UTC, lewey approved these changes

2023-09-27 09:07 UTC, merged